core/urls.py
from django.urls import path
from .views import (ItemDetailView, contact, ItemsView, HomeView,
                    add_to_cart, remove_from_cart)
app_name = 'core'
urlpatterns = [
    path('produits/<slug>/', ItemDetailView, name='product'),
    path('contact/', contact, name='contact'),
    path('', HomeView, name='Home'),
    path('produits/', ItemsView.as_view(), name='products'),
    path('addToCart/<slug>/', add_to_cart, name='add_to_cart'),
    path('removeFromCart/<slug>/', remove_from_cart, name='remove_from_cart')
]

mobiliapro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse


CATEGORY_CHOICES = (('S', 'Salon'),
                    ('SW', 'Cuisine'),
                    ('OW', 'Chambre'),
                    ('AU', 'Autre'))

COLOR_CHOICES = (('P', 'primary'),
                 ('S', 'secondary'),
                 ('D', 'danger'))

PRODUCT_CATEGORY = (('MT', 'Meuble TV'),
                    ('TM', 'Table à manger'),
                    ('T', 'Table'),
                    ('RA', 'Rangement'),
                    ('C', 'Cuisine'),
                    ('BU', 'Bureau'))

INVENTORY_STATES = (('P', 'Disponible'),
                    ('D', 'Indisponible'))


class Home(models.Model):
    title = models.CharField(max_length=100)
    slider_image = models.ImageField(
        blank=True, upload_to='home/images/')

    def __str__(self):
        return self.title


class Item(models.Model):
    """
    individual item data
    """
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    color = models.CharField(choices=COLOR_CHOICES, max_length=3, default="P")
    inventory = models.CharField(
        choices=INVENTORY_STATES, max_length=2, default="P")
    product_category = models.CharField(
        choices=PRODUCT_CATEGORY, max_length=3, default="RA")
    slug = models.SlugField()
    description = models.TextField()
    image = models.FileField(blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={"slug": self.slug})

    def get_add_to_cart_url(self):
        return reverse('core:add_to_cart', kwargs={"slug": self.slug})

    def get_remove_from_cart_url(self):
        return reverse('core:remove_from_cart', kwargs={"slug": self.slug})


class ItemImage(models.Model):
    item = models.ForeignKey(Item, default=None, on_delete=models.CASCADE)
    images = models.FileField(upload_to='images/')
    number = models.IntegerField(default=1)
    caption = models.CharField(blank=True, max_length=30)

    def __str__(self):
        return self.item.title


class OrderItem(models.Model):
    """
    item list to be in Order
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return (self.quantity * self.item.price)

    def get_total_item_discountPrice(self):
        return (self.quantity * self.item.discount_price)


class Order(models.Model):
    """
    user Order
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, View
from django.utils import timezone
from django.contrib import messages
from .models import Item, ItemImage, OrderItem, Order, Home


def contact(request):
    """
    docstring
    """
    return render(request, "contact.html")


def HomeView(request):
    home = Home.objects.all()
    return render(request, 'home.html', {'home': home})


def ItemDetailView(request, slug):
    item = get_object_or_404(Item, slug=slug)
    photos = ItemImage.objects.filter(item=item)
    return render(request, 'product.html', {
        'object': item,
        'photos': photos
    })


class ItemsView(ListView):
    model = Item
    template_name = "products.html"


@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, create = OrderItem.objects.get_or_create(
        item=item, user=request.user, ordered=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, message="this item quantity was updated.")
            return redirect("core:product", slug=slug)
        else:
            messages.info(request, message="this item was added to your cart.")
            order.items.add(order_item)
            return redirect("core:product", slug=slug)
    else:
        order_date = timezone.now()
        order = Order.objects.create(
            user=request.user, ordered_date=order_date)
        order.items.add(order_item)
        messages.info(request, message="this item was added to your cart.")
        return redirect("core:product", slug=slug)


@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item, user=request.user, ordered=False)[0]
            order.items.remove(order_item)
            messages.info(
                request, message="this item was removed from your cart.")
            return redirect("core:product", slug=slug)
        else:
            messages.info(request, message="this item was not in your cart.")
            return redirect("core:product", slug=slug)
    else:
        messages.info(request, message="you do not have an acive order")
        return redirect("core:product", slug=slug)

core/templates/checkout.html
<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
</style>
<link href={% static 'form-validation.css' %} rel="stylesheet" />

<div class="container">
  <div class="py-5 text-center">
    <img class="d-block mx-auto mb-4" src="#" alt="" width="72" height="72" />
    <h2>Checkout form</h2>
    <p class="lead">
      Below is an example form built entirely with Bootstrap’s form controls.
      Each required form group has a validation state that can be triggered by
      attempting to submit the form without completing it.
    </p>
  </div>

  <div class="row">
    <div class="col-md-4 order-md-2 mb-4">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">3</span>
      </h4>
      <ul class="list-group mb-3">
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">Product name</h6>
            <small class="text-muted">Brief description</small>
          </div>
          <span class="text-muted">$12</span>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">Second product</h6>
            <small class="text-muted">Brief description</small>
          </div>
          <span class="text-muted">$8</span>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">Third item</h6>
            <small class="text-muted">Brief description</small>
          </div>
          <span class="text-muted">$5</span>
        </li>
        <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Promo code</h6>
            <small>EXAMPLECODE</small>
          </div>
          <span class="text-success">-$5</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>Total (USD)</span>
          <strong>$20</strong>
        </li>
      </ul>

      <form class="card p-2">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Promo code" />
          <div class="input-group-append">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </div>
      </form>
    </div>
    <div class="col-md-8 order-md-1">
      <h4 class="mb-3">Billing address</h4>
      <form class="needs-validation" novalidate>
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="firstName">First name</label>
            <input
              type="text"
              class="form-control"
              id="firstName"
              placeholder=""
              value=""
              required
            />
            <div class="invalid-feedback">Valid first name is required.</div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="lastName">Last name</label>
            <input
              type="text"
              class="form-control"
              id="lastName"
              placeholder=""
              value=""
              required
            />
            <div class="invalid-feedback">Valid last name is required.</div>
          </div>
        </div>

        <div class="mb-3">
          <label for="username">Username</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">@</span>
            </div>
            <input
              type="text"
              class="form-control"
              id="username"
              placeholder="Username"
              required
            />
            <div class="invalid-feedback" style="width: 100%">
              Your username is required.
            </div>
          </div>
        </div>

        <div class="mb-3">
          <label for="email"
            >Email <span class="text-muted">(Optional)</span></label
          >
          <input
            type="email"
            class="form-control"
            id="email"
            placeholder="you@example.com"
          />
          <div class="invalid-feedback">
            Please enter a valid email address for shipping updates.
          </div>
        </div>

        <div class="mb-3">
          <label for="address">Address</label>
          <input
            type="text"
            class="form-control"
            id="address"
            placeholder="1234 Main St"
            required
          />
          <div class="invalid-feedback">
            Please enter your shipping address.
          </div>
        </div>

        <div class="mb-3">
          <label for="address2"
            >Address 2 <span class="text-muted">(Optional)</span></label
          >
          <input
            type="text"
            class="form-control"
            id="address2"
            placeholder="Apartment or suite"
          />
        </div>

        <div class="row">
          <div class="col-md-5 mb-3">
            <label for="country">Country</label>
            <select class="custom-select d-block w-100" id="country" required>
              <option value="">Choose...</option>
              <option>United States</option>
            </select>
            <div class="invalid-feedback">Please select a valid country.</div>
          </div>
          <div class="col-md-4 mb-3">
            <label for="state">State</label>
            <select class="custom-select d-block w-100" id="state" required>
              <option value="">Choose...</option>
              <option>California</option>
            </select>
            <div class="invalid-feedback">Please provide a valid state.</div>
          </div>
          <div class="col-md-3 mb-3">
            <label for="zip">Zip</label>
            <input
              type="text"
              class="form-control"
              id="zip"
              placeholder=""
              required
            />
            <div class="invalid-feedback">Zip code required.</div>
          </div>
        </div>
        <hr class="mb-4" />
        <div class="custom-control custom-checkbox">
          <input
            type="checkbox"
            class="custom-control-input"
            id="same-address"
          />
          <label class="custom-control-label" for="same-address"
            >Shipping address is the same as my billing address</label
          >
        </div>
        <div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" id="save-info" />
          <label class="custom-control-label" for="save-info"
            >Save this information for next time</label
          >
        </div>
        <hr class="mb-4" />

        <h4 class="mb-3">Payment</h4>

        <div class="d-block my-3">
          <div class="custom-control custom-radio">
            <input
              id="credit"
              name="paymentMethod"
              type="radio"
              class="custom-control-input"
              checked
              required
            />
            <label class="custom-control-label" for="credit">Credit card</label>
          </div>
          <div class="custom-control custom-radio">
            <input
              id="debit"
              name="paymentMethod"
              type="radio"
              class="custom-control-input"
              required
            />
            <label class="custom-control-label" for="debit">Debit card</label>
          </div>
          <div class="custom-control custom-radio">
            <input
              id="paypal"
              name="paymentMethod"
              type="radio"
              class="custom-control-input"
              required
            />
            <label class="custom-control-label" for="paypal">PayPal</label>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="cc-name">Name on card</label>
            <input
              type="text"
              class="form-control"
              id="cc-name"
              placeholder=""
              required
            />
            <small class="text-muted">Full name as displayed on card</small>
            <div class="invalid-feedback">Name on card is required</div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="cc-number">Credit card number</label>
            <input
              type="text"
              class="form-control"
              id="cc-number"
              placeholder=""
              required
            />
            <div class="invalid-feedback">Credit card number is required</div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3 mb-3">
            <label for="cc-expiration">Expiration</label>
            <input
              type="text"
              class="form-control"
              id="cc-expiration"
              placeholder=""
              required
            />
            <div class="invalid-feedback">Expiration date required</div>
          </div>
          <div class="col-md-3 mb-3">
            <label for="cc-cvv">CVV</label>
            <input
              type="text"
              class="form-control"
              id="cc-cvv"
              placeholder=""
              required
            />
            <div class="invalid-feedback">Security code required</div>
          </div>
        </div>
        <hr class="mb-4" />
        <button class="btn btn-primary btn-lg btn-block" type="submit">
          Continue to checkout
        </button>
      </form>
    </div>
  </div>
</div>

core/templates/product.html
{% extends "index.html" %} {% load static %} {% block content %}

<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"> 
<script src="{% static 'js/jquery.magnific-popup.js' %}"></script> 
<style>


  img {
    pointer-events: none;
    box-shadow: 0 2px 4px 0 rgba(0,0,0,0.4);
}
.zoom {
  
  transition: transform .3s ease-in-out;
}

.zoom:hover {
  transform: scale(1.1); 
}

.carousel-item:hover{
  filter: brightness(1.05);
  transition: transform .2s ease;
  cursor:pointer;
}
 
.carousel-item{
  height: 100%;
 
}


.carousel-item img{
  height:100%;
  width:auto;
  border-radius: 2%;
}


@media screen and (max-width: 767px) {
.carousel-item img{
  max-height: 45vh;
  width:auto;
}
}

@media screen and (max-width: 1199px) {
.carousel-item img{
  max-height: 60vh;
  height: 60vh;
  width:auto;
}
}


@media screen and (min-width: 1200px) {
.carousel-item img{
  max-height: 80vh;
  height:80vh;
  width:auto;
}
}

.carousel-indicators {
  position: initial;
  right: initial;
  bottom: initial;
  left: initial;
  z-index: initial;
  display: initial;
  -ms-flex-pack: initial;
  justify-content: initial;
  padding-left: initial;
  margin-right: initial;
  margin-left: initial;
  list-style: initial; 
}
.carousel-indicators .img-ind {
  width: auto;
  height: auto;
  text-indent: 0;
  border: none;
 
}
.carousel-indicators .img-ind img {
  border-radius: 10%;
  max-height: 100px;
}
.carousel-indicators .img-ind.active img {
  border:2px solid #089168 ;
  border-radius: 10%;
  -webkit-transition: all 0.3s ease;
  -moz-transition: all 0.3s ease;
  transition: all 0.3s ease;
  
}
.carousel-indicators .img-ind.active {
  background-color:white;
}

.mobilep{
  position: absolute;
  top: 50%;
  background-color:rgba(0, 0, 0, 0.5);
  border-radius: 25%;
}
.mobilen{
  position: absolute;
  top: 50%;
  transform: translateX(-100%);
  background-color:rgba(0, 0, 0, 0.5);
  border-radius: 25%;
}

.informations a {
  text-decoration: none;
  margin: 1rem 0;
  font-weight: 600; 
  text-transform: uppercase;
  font-size: var(--small-font-size);
  letter-spacing: 1px;
}

.informations p {
  font-size: var(--normal-font-size);
  margin: 1rem 0;
  line-height: 1.5;
}

.informations {
  max-width: 95%;
  margin: 0 auto;
  width: 95%;
  text-align: center;
  padding-bottom: 1rem;
  
}

.informations h3 {
  font-family: 'Montserrat', sans-serif;
  font-weight: 600;
  color: #333;
  font-size: 1.825rem;
  margin: 1.3rem 0;
}

.service a {
  color: #5b7abb;
  display: block;
}

.service h4 {
  font-family: 'Montserrat', sans-serif;
  font-weight: 600;
  color: #56ceba;
  font-size: 1.3rem;
  margin: 1rem 0 0.6rem;
}

.service {
  background: white;
  -webkit-tap-highlight-color: transparent;
  padding:10px;
  border-radius: 4px;
  text-align: center;
  display: flex;
  flex-wrap: wrap;
  border: 3px solid #e7e7e7;
  -webkit-transition: all 0.3s ease;
  -moz-transition: all 0.3s ease;
  transition: all 0.3s ease;
 
}

.service:hover {
  -webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.08);
  -moz-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.08);
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.08);
 
}


.service1 h4,
.service1 .cta {
  color: #15887c;
}

.service1:hover {
  border: 3px solid rgb(0,128, 0);
}

.service2 h4,
.service2 .cta {
  color: #ca4242;
}

.service2:hover {
  border: 3px solid #ca4242;
}

.service > * {
  flex: 1 1 100%;
}
.breadcrumb{
  background-color:white;
  
}
</style>


  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href={% url 'core:products' %}>Produits</a></li>
      <li class="breadcrumb-item active"  aria-current="page">{{object.title}}</li>
      </ol>
    </nav>
  </div>
  <div class="container marketing ">
  <div class="row">
  <div  class="informations">
    <div class="service service1">
        <div id="Carousel" class="carousel slide carousel-fade" data-touch="true" data-ride="carousel">
       
          <div class="row">
            <div class=" col-sm-2 d-none d-md-block">
              <ol class="carousel-indicators list-group">
                  {% for p in photos %}
                  <li data-target="#Carousel" data-slide-to='{{ forloop.counter0 }}' class="{% if forloop.counter0 == 0 %} active {% endif %} list-group-item p-0 mb-2 zoom img-ind"><img src="{{p.images.url}}" alt="" class="img-fluid"/></li>
                  {% endfor %}
                </ol>
              </div>
           <div class="carousel-inner col-md-10 col-sm-12">
            
                
              {% for p in photos %}
              
              <div class="{% if forloop.counter0 == 0 %}  active {% endif %} carousel-item" href="{{p.images.url}}" data-interval="50000">
                
                <img src="{{p.images.url}}" alt="product image" class="img-fluid" />  
              
              </div>
              {% endfor %}
           
          {% if   photos|length >= 2 %}
            <a class="carousel-control-prev d-md-none d-sm-block" href="#Carousel" role="button" data-slide="prev" >
              <span class="mobilep carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next d-md-none d-sm-block" href="#Carousel" role="button" data-slide="next">
              <span class="mobilen  carousel-control-next-icon" aria-hidden="true" ></span>
              <span class="sr-only">Next</span>
            </a>
          {% endif %}       
          </div>

        </div>
      </div>
    </div> 
  </div>
</div> 
</div>
                                                    
<div class="container marketing mt-1">
    
  <div class="row ">
   
        
          <div  class="informations">
            <div class="service service2">

      <h4>le produit</h4>
      <p><strong style="font-weight: 600;font-size: 16px;">La description : </strong>{{object.description}}</p>
      
      <p>
        <strong style="font-weight: 600; font-size: 16px;">le prix : </strong>{{object.discount_price}} <strong style="font-weight: 600;font-size: 16px;">DA</strong>
      </p>
    
   
      </div>
      </div>
  </div>
</div>



<script type="text/javascript">
$('.carousel-inner').magnificPopup({
  delegate: 'div',
  type: 'image',
   gallery:{enabled:true,}, 
  zoom: {
    enabled: true,}
});
</script>

{% endblock content %}

core/templates/products.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

 <style>


.card {
  box-shadow: 0 2px 4px 0 rgba(0,0,0,0.4);
  transition: 0.3s;
  
}

.product-area{
  padding-top: 1rem;
}

.product{
padding: 1rem;
}

 .card:hover {
  box-shadow: 1px 8px 16px  rgba(38, 38, 38, 0.563);
}

.card-img-top{
  height:250px;
}
.card:hover {
  filter: brightness(1.10) ;
}

.btn,
.btn a{
 
  border: none;
  color: #FFFFFF;
  text-align: center;
  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
    -webkit-appearance: none;
  background-color: #E95151;
  border-radius: 4rem;
  box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  outline: none;
  -webkit-tap-highlight-color: transparent;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

.btn span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.btn span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.btn:hover span {
  padding-right: 25px;
}

.btn:hover span:after {
  opacity: 1;
  right: 0;
}
.filter-panel {
  display: flex;
  margin-bottom: 15px ;
  padding:0;
        
        }
.filter-panel li {
  font-size: 14px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  box-sizing: border-box;
  width: 80px;
  margin: 3px ;
  padding: 5px  0;
  list-style: none;
  cursor: pointer;
  transition: all .5s;
  color: #fff;
  border-radius: 5px;
  background-color: #008B76;
}
.filter-panel li:hover {
    background-color: hsl(174, 100%, 35%);
}
.filter-panel strong {
    width: 120px;
}

.scrolltop {
    position: fixed;
    right: 1rem;
    bottom: -20%;
    display: flex;
    justify-content: center;
    align-items: center;
    padding: .3rem;
    background: rgba(6, 156, 84, .5);
    border-radius: .4rem;
    z-index: var(--z-tooltip);
    transition: .4s;
    visibility: hidden;
}

.scrolltop:hover {
    background-color: var(--first-color-alt);
    text-decoration: none;
}

.scrolltop__icon {
    font-size: 1.8rem;
    color: var(--body-color);
}

.show-scroll {
    visibility: visible;
    bottom: 1.5rem;
}
</style>

<a href="#" class="scrolltop" id="scroll-top">
  <i class='bx bx-chevron-up scrolltop__icon'></i>
</a>

      <section class="product-area">
    
         <div class="container products">
        
          <ul class="filter-panel">
            <li data-filter="all"> Tous </li>
            <li data-filter="Salon"> Salon</li>
            <li data-filter="Cuisine">Cuisine</li>
            <li data-filter="Chambre">Chambre</li>
            <li data-filter="Autre">Autres</li>
        </ul>
  

        <div class="row">
            <div class="filter-container">
      {% for item in object_list %}
     
          
            <div class="col-lg-4 col-md-6 product filtr-item" data-category="{{item.get_category_display}}"  >
              <div class="card">
                <div class="card-img">
                <a href="{{item.get_absolute_url}}" >
                <img class="card-img-top" src="{{item.image.url}}" oncontextmenu="return false;" alt="Card image cap">
              </a>
            </div>
                <div class="card-body">
                
                  <p class="card-text text-muted pt-2 pb-2">nom: {{item.title}}</p>
                  <p class="card-text text-muted pb-2">catégorie: {{item.get_product_category_display}}</p>
                  <p class="card-text text-muted pb-4">colour: {{item.get_color_display}}</p>
               
                  <div class="d-flex  justify-content-between align-items-center">
                    <a  href="{{item.get_absolute_url}}" >
                      <button class="btn update-cart"  type="button" >
                    
                        <span>Détails</span>
                      
                      </button>
                    </a>
                    <small class="text-muted"> 
                       <p class="card-text">{{item.get_inventory_display}}</p>
                      
                    </small>
                  </div>
                </div>
              </div>
            </div>
          
    {% endfor %}
            </div>
            </div>
          </div>
          </section>
     
      <script>
const options = { };

const filterizr = new Filterizr('.filter-container', options);

function scrollTop(){
    const scrollTop = document.getElementById('scroll-top');
    if(this.scrollY >= 1960) scrollTop.classList.add('show-scroll'); else scrollTop.classList.remove('show-scroll')
}
window.addEventListener('scroll', scrollTop)
      </script> 


  
   
{% endblock content %}